name: Release application

on:
    workflow_dispatch:
    push:
        branches:
            - "main"

permissions:
    id-token: write
    contents: read

jobs:
    publish:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith( github.event.head_commit.message, '[release]' ) }}
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Update NPM
              run: npm install -g npm@latest

            - name: Publish to NPM registry
              run: npm publish

    build-linux:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith( github.event.head_commit.message, '[release]' ) }}
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Cache node_modules
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Install dependencies
              run: npm install

            - name: Build & release app (Linux)
              run: npm run build -- --publish always --linux
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}

    build-windows:
        timeout-minutes: 10
        runs-on: windows-latest
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith( github.event.head_commit.message, '[release]' ) }}
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Cache node_modules
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Install dependencies
              run: npm install

            - name: Build & release app (Windows)
              run: npm run build -- --publish always --win
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}

    build-macos:
        timeout-minutes: 10
        runs-on: macos-latest
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith( github.event.head_commit.message, '[release]' ) }}
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Cache node_modules
              uses: actions/cache@v5
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Install dependencies
              run: npm install

            - name: Build & release app (MacOS)
              if: ${{ matrix.os == 'macos-latest' }}
              run: npm run build -- --publish always --mac
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  CSC_LINK: ${{ secrets.CSC_LINK }}
